apiVersion: v1
kind: Service
metadata:
  name: sqlmcpserver
  namespace: sqlmcpserver
  labels:
    app.kubernetes.io/name: sqlmcpserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sqlmcpserver
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
